# Generated by Django 3.0.5 on 2020-08-14 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
                ('mensaje', models.TextField(max_length=350)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.IntegerField(default=0)),
                ('inscriptos', models.IntegerField(default=0)),
                ('turno', models.CharField(blank=True, choices=[('NOCHE', 'noche'), ('TARDE', 'tarde'), ('MAÑANA', 'manaña')], max_length=50)),
                ('descripcion', models.TextField(default=None, max_length=350, null=True)),
                ('imagen', models.ImageField(default=None, null=True, upload_to='web/static/web/')),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('edad', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=254)),
                ('dni', models.IntegerField(default=0)),
                ('telefono', models.IntegerField(default=0)),
                ('cursos', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='web.Curso')),
            ],
        ),
    ]
