# Generated by Django 3.0.5 on 2020-08-14 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='imagen',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='web/static/web/'),
        ),
    ]
