# Generated by Django 3.0.8 on 2020-08-06 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='price',
            new_name='inscriptos',
        ),
        migrations.RenameField(
            model_name='curso',
            old_name='name',
            new_name='nombre',
        ),
        migrations.AddField(
            model_name='curso',
            name='descripcion',
            field=models.TextField(default=None, max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='imagen',
            field=models.ImageField(default=None, null=True, upload_to='web/static/web/'),
        ),
        migrations.AddField(
            model_name='curso',
            name='precio',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('edad', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=254)),
                ('cursos', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='web.Curso')),
            ],
        ),
    ]
