# Generated by Django 3.0.8 on 2020-07-30 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='curso',
            old_name='price',
            new_name='precio',
        ),
        migrations.AddField(
            model_name='curso',
            name='descripcion',
            field=models.TextField(default=None, max_length=350),
        ),
    ]
