# Generated by Django 3.0.8 on 2020-07-30 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20200730_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='descripcion',
            field=models.TextField(default=None, max_length=350, null=True),
        ),
    ]
