# Generated by Django 3.0.8 on 2020-08-06 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20200806_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='dni',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='alumno',
            name='telefono',
            field=models.IntegerField(default=0),
        ),
    ]
