# Generated by Django 3.0.8 on 2020-07-31 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20200730_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='imagen',
            field=models.ImageField(default=None, null=True, upload_to='web/static/web/'),
        ),
    ]
