# Generated by Django 3.0.8 on 2020-07-23 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20200723_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='turno',
            field=models.CharField(blank=True, choices=[('NOCHE', 'noche'), ('TARDE', 'tarde'), ('MAÑANA', 'manaña')], max_length=50),
        ),
    ]
