# Generated by Django 3.0.8 on 2020-07-31 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_curso_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='inscriptos',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('edad', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=254)),
                ('cursos', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='web.Curso')),
            ],
        ),
    ]
