# Generated by Django 3.0.8 on 2020-07-24 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_curso_turno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
                ('mensaje', models.TextField(max_length=350)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
