# Generated by Django 3.0.8 on 2020-07-25 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_contacto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='price',
            new_name='inscriptos',
        ),
        migrations.RenameField(
            model_name='curso',
            old_name='name',
            new_name='nombre',
        ),
    ]
