# Generated by Django 3.0.8 on 2020-07-25 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20200725_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='imagen',
            field=models.ImageField(default=None, null=True, upload_to='web/static/web/'),
        ),
    ]
